#!/usr/bin/env bash
# Run a single promptfoo suite and append results to the tracker.
#
# Usage:
#   ./scripts/run-suite.sh exegetical-notes:red
#   ./scripts/run-suite.sh exegetical-notes:green
#   ./scripts/run-suite.sh all          # run every suite sequentially
#   ./scripts/run-suite.sh smoke        # just the CLI provider smoke test
#
# Results are appended to results/tracker.md (a persistent Markdown table).
# Each run also saves JSON output to results/<suite>-<timestamp>.json.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RESULTS_DIR="$ROOT/results"
TRACKER="$RESULTS_DIR/tracker.md"

mkdir -p "$RESULTS_DIR"

ts() { date "+%Y-%m-%d %H:%M:%S"; }
ts_short() { date "+%Y-%m-%dT%H:%M:%S"; }

# Initialize tracker file if it doesn't exist
if [[ ! -f "$TRACKER" ]]; then
  cat > "$TRACKER" << 'EOF'
# Promptfoo Eval Tracker

> Auto-generated by `scripts/run-suite.sh`. Do not edit manually.

| Timestamp | Suite | Phase | Tests | Pass | Fail | Error | Duration | Eval ID | Provider |
|-----------|-------|-------|-------|------|------|-------|----------|---------|----------|
EOF
  echo "[$(ts)] Created $TRACKER"
fi

# Map suite name to config path and phase
resolve_suite() {
  local suite="$1"
  local config=""
  local phase=""

  case "$suite" in
    # Skills
    exegetical-notes:red)    config="skills/exegetical-notes/promptfooconfig-red.yaml"; phase="RED" ;;
    exegetical-notes:green)  config="skills/exegetical-notes/promptfooconfig-green.yaml"; phase="GREEN" ;;
    argument-flow:red)       config="skills/argument-flow/promptfooconfig-red.yaml"; phase="RED" ;;
    argument-flow:green)     config="skills/argument-flow/promptfooconfig-green.yaml"; phase="GREEN" ;;
    pericope-delimitation:red)    config="skills/pericope-delimitation/promptfooconfig-red.yaml"; phase="RED" ;;
    pericope-delimitation:green)  config="skills/pericope-delimitation/promptfooconfig-green.yaml"; phase="GREEN" ;;
    consult-biblical-scholar:red)    config="skills/consult-biblical-scholar/promptfooconfig-red.yaml"; phase="RED" ;;
    consult-biblical-scholar:green)  config="skills/consult-biblical-scholar/promptfooconfig-green.yaml"; phase="GREEN" ;;
    biblical-segmentation:red)    config="skills/biblical-segmentation/promptfooconfig-red.yaml"; phase="RED" ;;
    biblical-segmentation:green)  config="skills/biblical-segmentation/promptfooconfig-green.yaml"; phase="GREEN" ;;
    # Agents
    data-retriever:red)      config="agents/data-retriever/promptfooconfig-red.yaml"; phase="RED" ;;
    biblical-scholar:red)    config="agents/biblical-scholar/promptfooconfig-red.yaml"; phase="RED" ;;
    study-evaluator:red)     config="agents/study-evaluator/promptfooconfig-red.yaml"; phase="RED" ;;
    # Special
    smoke)                   config="smoke/promptfooconfig-cli-provider.yaml"; phase="SMOKE" ;;
    regression)              config="smoke/promptfooconfig-regression.yaml"; phase="REGR" ;;
    calibration)             config="assertions/grader-calibration.yaml"; phase="CAL" ;;
    *)
      echo "Unknown suite: $suite" >&2
      echo "Available: exegetical-notes:{red,green} argument-flow:{red,green} pericope-delimitation:{red,green}" >&2
      echo "           consult-biblical-scholar:{red,green} biblical-segmentation:{red,green}" >&2
      echo "           data-retriever:red biblical-scholar:red study-evaluator:red" >&2
      echo "           smoke regression calibration" >&2
      exit 1
      ;;
  esac

  echo "$config|$phase"
}

# All suites in recommended order
ALL_SUITES=(
  "smoke"
  "calibration"
  "regression"
  "exegetical-notes:red"
  "exegetical-notes:green"
  "argument-flow:red"
  "argument-flow:green"
  "pericope-delimitation:red"
  "pericope-delimitation:green"
  "consult-biblical-scholar:red"
  "consult-biblical-scholar:green"
  "biblical-segmentation:red"
  "biblical-segmentation:green"
  "data-retriever:red"
  "biblical-scholar:red"
  "study-evaluator:red"
)

run_one() {
  local suite="$1"
  local resolved
  resolved=$(resolve_suite "$suite")
  local config="${resolved%%|*}"
  local phase="${resolved##*|}"
  local config_path="$ROOT/$config"

  if [[ ! -f "$config_path" ]]; then
    echo "[$(ts)] SKIP: $config_path not found"
    echo "| $(ts_short) | $suite | $phase | - | - | - | CONFIG_NOT_FOUND | - | - | - |" >> "$TRACKER"
    return 1
  fi

  # Count tests in config
  local test_count
  test_count=$(grep -c "^  - description:" "$config_path" 2>/dev/null || echo "?")

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "[$(ts)] RUNNING: $suite ($phase) — $test_count tests"
  echo "[$(ts)] Config:  $config"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  local json_out="$RESULTS_DIR/${suite//:/--}-$(date +%Y%m%dT%H%M%S).json"
  local start_ts
  start_ts=$(date +%s)

  local exit_code=0
  CLAUDECODE= npx promptfoo eval \
    --no-cache \
    -c "$config" \
    --output "$json_out" \
    2>&1 | tee "$RESULTS_DIR/.last-run.log" || exit_code=$?

  local end_ts
  end_ts=$(date +%s)
  local duration=$(( end_ts - start_ts ))
  local duration_str="${duration}s"
  if [[ $duration -gt 60 ]]; then
    duration_str="$(( duration / 60 ))m$(( duration % 60 ))s"
  fi

  # Extract results from output
  local pass_count fail_count error_count eval_id provider
  pass_count=$(grep -oE "[0-9]+ passed" "$RESULTS_DIR/.last-run.log" | tail -1 | grep -oE "[0-9]+" || echo "0")
  fail_count=$(grep -oE "[0-9]+ failed" "$RESULTS_DIR/.last-run.log" | tail -1 | grep -oE "[0-9]+" || echo "0")
  error_count=$(grep -oE "[0-9]+ error" "$RESULTS_DIR/.last-run.log" | tail -1 | grep -oE "[0-9]+" || echo "0")
  eval_id=$(grep -oE "eval-[a-zA-Z0-9_-]+" "$RESULTS_DIR/.last-run.log" | tail -1 || echo "-")
  provider=$(grep -oE "(cli-bare|cli-with-skill|without-skill|with-skill)" "$RESULTS_DIR/.last-run.log" | head -1 || echo "-")

  # Print summary
  echo ""
  if [[ "$exit_code" -eq 0 && "$fail_count" == "0" && "$error_count" == "0" ]]; then
    echo "[$(ts)] PASS  $suite — ${pass_count} passed in $duration_str"
  elif [[ "$exit_code" -ne 0 ]]; then
    echo "[$(ts)] ERROR $suite — exit code $exit_code in $duration_str"
  else
    echo "[$(ts)] FAIL  $suite — ${pass_count} passed, ${fail_count} failed, ${error_count} errors in $duration_str"
  fi

  # Append to tracker
  echo "| $(ts_short) | $suite | $phase | $test_count | $pass_count | $fail_count | $error_count | $duration_str | $eval_id | $provider |" >> "$TRACKER"

  echo "[$(ts)] JSON: $json_out"
  return $exit_code
}

# Main
SUITE="${1:-}"

if [[ -z "$SUITE" ]]; then
  echo "Usage: $0 <suite-name|all>"
  echo ""
  echo "Suites:"
  for s in "${ALL_SUITES[@]}"; do
    echo "  $s"
  done
  exit 1
fi

if [[ "$SUITE" == "all" ]]; then
  echo "=============================================="
  echo "  Running ALL suites (${#ALL_SUITES[@]} total)"
  echo "  Results: $TRACKER"
  echo "=============================================="

  TOTAL=0
  PASSED=0
  FAILED=0

  for s in "${ALL_SUITES[@]}"; do
    TOTAL=$((TOTAL + 1))
    if run_one "$s"; then
      PASSED=$((PASSED + 1))
    else
      FAILED=$((FAILED + 1))
    fi
  done

  echo ""
  echo "=============================================="
  echo "  ALL SUITES COMPLETE"
  echo "  Total: $TOTAL  Passed: $PASSED  Failed: $FAILED"
  echo "  Tracker: $TRACKER"
  echo "=============================================="
else
  run_one "$SUITE"
fi
