#!/usr/bin/env python3
"""
Masoretic Paragraph Marker Loader

Loads OT Masoretic paragraph markers from the committed schema-v2 JSON files
under `reference/masoretic/`, which are generated by
`extract_oshb_paragraphs.py` from pinned OSHB XML. This module only READS and
reformats that data — it does not extract it. (The name is historical; renaming
it would ripple into a file issue #120 owns.)

Usage:
    python sefaria_paragraphs.py Genesis
    python sefaria_paragraphs.py "1 Samuel"
    python sefaria_paragraphs.py Isaiah --output json

Output:
    Paragraph-break records: reference, chapter, verse, type, position.

IMPORTANT for consumers — `position` is not decoration:
    Only `position == "verse_end"` supports a claim that a passage ends after
    that verse. 90 of the 3,162 corpus markers sit WITHIN a verse; treating one
    of those as a verse boundary certifies a claim the manuscript does not make.
    A `within_verse` marker attests an internal subdivision — real evidence,
    but for a different claim.
"""


import argparse
import json
import sys
from pathlib import Path
from typing import Optional

from bible_utils import (
    normalize_book_name,
    load_json_file,
    validate_verse_reference
)


def load_book_data(book: str) -> Optional[dict]:
    """
    Load JSON data for a book from static files.

    Args:
        book: Book name (e.g., "Genesis", "1 Samuel")

    Returns:
        Dict with 'petuchot' and 'setumot' lists, or None if not found.
    """
    script_dir = Path(__file__).parent
    json_file = script_dir.parent / "reference" / "masoretic" / f"{normalize_book_name(book)}.json"
    return load_json_file(json_file)


def marker_layer_absent(book: str) -> bool:
    """True if this book carries no paragraph-marker layer in this witness.

    Psalms and Obadiah carry zero markers. For Psalms this is structural: its
    canonical chapter division IS the manuscript paragraph division, so the
    scribal marker layer is unused.

    Consumers must distinguish this from "no marker found here". An absent
    layer means the instrument does not apply to this book; reporting it as a
    non-finding reads as evidence AGAINST a proposed boundary when it is
    nothing of the kind.
    """
    data = load_book_data(book)
    if data is None:
        return False
    return 'marker_layer_absent' in data.get('_metadata', {})


def get_paragraph_breaks(book: str) -> list[dict]:
    """
    Load paragraph breaks from the committed schema-v2 data.

    Returns a list of records with reference, chapter, verse, type, and
    position. Multiple markers in one verse yield multiple records — 30 verses
    carry more than one, and collapsing them would discard genuine markers.

    Returns [] (never raises) on unreadable or non-v2 data: verify_claims.py
    calls this with no try/except and converts a falsy result into a correct
    UNVERIFIABLE verdict, so raising would crash a file issue #120 owns.
    """
    data = load_book_data(book)
    if data is None:
        return []

    # Absent schema_version is treated as v1. This is deliberate: a v1 tree
    # read by this v2-aware loader must degrade visibly rather than silently
    # mis-parse.
    if data.get('schema_version') != 2:
        print(
            f"Warning: {book} data is not schema_version 2 "
            f"(got {data.get('schema_version')!r}); refusing to parse. "
            f"Regenerate with extract_oshb_paragraphs.py.",
            file=sys.stderr,
        )
        return []

    breaks = []
    skipped = 0

    for marker in data.get('markers', []):
        verse_ref = f"{marker.get('chapter')}:{marker.get('verse')}"
        try:
            is_valid, chapter, verse = validate_verse_reference(verse_ref)
            if not is_valid:
                print(
                    f"Warning: Skipping malformed reference '{verse_ref}'",
                    file=sys.stderr,
                )
                skipped += 1
                continue

            breaks.append({
                'reference': f"{book} {verse_ref}",
                'chapter': int(chapter),
                'verse': int(verse),
                'type': marker['type'],
                # Additive keys. `position` is what makes a boundary claim
                # checkable; ordinal keeps same-verse markers distinct.
                'position': marker.get('position'),
                'ordinal_in_verse': marker.get('ordinal_in_verse'),
            })
        except Exception as e:
            print(f"Warning: Skipping reference '{verse_ref}': {e}", file=sys.stderr)
            skipped += 1

    # Stable within a verse: ordinal preserves source document order, so two
    # markers on one verse keep the order the manuscript gives them.
    breaks.sort(key=lambda x: (x['chapter'], x['verse'], x.get('ordinal_in_verse') or 0))

    if skipped > 0:
        print(f"Skipped {skipped} malformed entries", file=sys.stderr)

    return breaks


def format_output(breaks: list[dict], output_format: str) -> str:
    """Format the breaks for output."""
    if output_format == 'json':
        return json.dumps(breaks, indent=2)

    # Default: human-readable
    lines = []
    current_chapter = None

    for b in breaks:
        if b['chapter'] != current_chapter:
            if current_chapter is not None:
                lines.append('')
            current_chapter = b['chapter']
            lines.append(f"Chapter {current_chapter}:")

        marker_symbol = 'פ' if b['type'] == 'petuchah' else 'ס'
        pos = b.get('position') or 'unknown'
        note = '' if pos == 'verse_end' else '  [not a verse boundary]'
        lines.append(f"  {b['reference']} ({marker_symbol} {b['type']}, {pos}){note}")

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Extract paragraph markers from OT books (static data)'
    )
    parser.add_argument('book', help='Book name (e.g., "Genesis", "1 Samuel")')
    parser.add_argument(
        '--output', '-o',
        choices=['text', 'json'],
        default='text',
        help='Output format (default: text)'
    )

    args = parser.parse_args()

    print(f"Loading paragraph markers for {args.book}...", file=sys.stderr)
    breaks = get_paragraph_breaks(args.book)

    if not breaks:
        print(f"No paragraph markers found for {args.book}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(breaks)} paragraph markers", file=sys.stderr)
    print(format_output(breaks, args.output))


if __name__ == '__main__':
    main()
