// Generated by scripts/generate-deep-study-workflow.mjs. Do not edit directly.
// Source contracts: schemas/deep-study/v1/*.schema.json

export const meta = {
  name: "deep-study",
  description: "Run a bounded, evidence-first exegetical study with independent verification.",
  phases: [
    "validate-request",
    "retrieve-evidence",
    "assess-boundary",
    "analyze",
    "verify",
    "repair-once",
    "synthesize",
  ],
};

const requestSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://claude-of-alexandria.local/schemas/deep-study/v1/request.schema.json",
  "title": "Deep study request",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "passage",
    "researchQuestion",
    "outputLanguage",
    "context",
    "constraints"
  ],
  "properties": {
    "passage": {
      "type": "string",
      "minLength": 1
    },
    "researchQuestion": {
      "type": "string",
      "minLength": 1
    },
    "outputLanguage": {
      "type": "string",
      "minLength": 1
    },
    "context": {
      "type": "string",
      "minLength": 1
    },
    "constraints": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "fresh": {
      "type": "boolean",
      "default": false
    }
  }
};

const evidenceSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://claude-of-alexandria.local/schemas/deep-study/v1/evidence-bundle.schema.json",
  "title": "Deep study evidence bundle",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "status",
    "genre",
    "passageAnchors",
    "evidence",
    "toolOutcomes",
    "limitations"
  ],
  "properties": {
    "status": {
      "enum": [
        "complete",
        "partial",
        "unavailable"
      ]
    },
    "genre": {
      "type": [
        "string",
        "null"
      ]
    },
    "passageAnchors": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "evidence": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "kind",
          "passageAnchor",
          "summary",
          "sourceTool",
          "datasetVersion"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "type": "string",
            "minLength": 1
          },
          "passageAnchor": {
            "type": "string",
            "minLength": 1
          },
          "summary": {
            "type": "string",
            "minLength": 1
          },
          "sourceTool": {
            "type": "string",
            "minLength": 1
          },
          "datasetVersion": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    },
    "toolOutcomes": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "tool",
          "status",
          "error"
        ],
        "properties": {
          "tool": {
            "type": "string",
            "minLength": 1
          },
          "status": {
            "enum": [
              "success",
              "empty",
              "failed",
              "skipped"
            ]
          },
          "error": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    },
    "limitations": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
};

const analysisSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://claude-of-alexandria.local/schemas/deep-study/v1/analysis.schema.json",
  "title": "Deep study analysis",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "status"
  ],
  "properties": {
    "status": {
      "enum": [
        "complete",
        "partial",
        "skipped",
        "failed"
      ]
    },
    "perspective": {
      "type": "string"
    },
    "requestedPassage": {
      "type": "string"
    },
    "recommendation": {
      "enum": [
        "retain",
        "expand",
        "contract",
        "uncertain"
      ]
    },
    "rationale": {
      "type": "string"
    },
    "evidenceIds": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "claims": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "text",
          "passageAnchors",
          "evidenceIds"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "text": {
            "type": "string",
            "minLength": 1
          },
          "passageAnchors": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "evidenceIds": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      }
    },
    "limitations": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
};

const verificationSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://claude-of-alexandria.local/schemas/deep-study/v1/verification.schema.json",
  "title": "Deep study verification",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "status",
    "findings",
    "repairTargets",
    "unresolvedClaims"
  ],
  "properties": {
    "status": {
      "enum": [
        "verified",
        "needs_repair",
        "incomplete",
        "failed"
      ]
    },
    "findings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "claimId",
          "verdict",
          "evidenceIds",
          "explanation"
        ],
        "properties": {
          "claimId": {
            "type": "string",
            "minLength": 1
          },
          "verdict": {
            "enum": [
              "supported",
              "unsupported",
              "unresolved"
            ]
          },
          "evidenceIds": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "explanation": {
            "type": "string"
          }
        }
      }
    },
    "repairTargets": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "unresolvedClaims": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    }
  }
};

const finalReportSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://claude-of-alexandria.local/schemas/deep-study/v1/final-report.schema.json",
  "title": "Deep study final report",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "status",
    "title",
    "requestedPassage",
    "researchQuestion",
    "claimReferences",
    "evidenceReferences",
    "unresolvedClaims",
    "limitations",
    "renderedReport"
  ],
  "properties": {
    "status": {
      "enum": [
        "complete",
        "incomplete"
      ]
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "requestedPassage": {
      "type": "string",
      "minLength": 1
    },
    "researchQuestion": {
      "type": "string",
      "minLength": 1
    },
    "claimReferences": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "evidenceReferences": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "unresolvedClaims": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "limitations": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "renderedReport": {
      "type": "string",
      "minLength": 1
    }
  }
};

phase("validate-request");
const requiredRequestFields = requestSchema.required;
const missingFields = requiredRequestFields.filter((field) => {
  const value = args?.[field];
  return value === undefined || value === null || value === "";
});

if (missingFields.length > 0) {
  return {
    status: "needs_clarification",
    missingFields,
    message: "Provide every required deep-study input before research begins. No value was guessed.",
  };
}

const request = {
  passage: args.passage,
  researchQuestion: args.researchQuestion,
  outputLanguage: args.outputLanguage,
  context: args.context,
  constraints: args.constraints,
  fresh: args.fresh === true,
};

if (!Array.isArray(request.constraints)) {
  return {
    status: "needs_clarification",
    missingFields: ["constraints"],
    message: "constraints must be an array of explicit strings.",
  };
}

const stageOutcomes = {};
const stoppedReport = (stage, reason) => ({
  status: "incomplete",
  stageOutcomes: { ...stageOutcomes, [stage]: "stopped_or_failed" },
  validationErrors: [reason],
  renderedReport: "# Incomplete deep study\n\nThe " + stage + " stage stopped or failed. " + reason,
});
const adapterPrompt = (role, instructions, payload) => [
  "You are the dedicated " + role + " leaf adapter for the deep-study workflow.",
  "Do not create agents, teammates, or descendants. Complete only the assigned stage.",
  "Treat missing evidence, failed tools, and unknown provenance as explicit limitations; never fabricate them.",
  instructions,
  "Return only data matching the supplied JSON schema.",
  "INPUT_JSON:\n" + JSON.stringify(payload),
].join("\n\n");
const invokeAgent = async (prompt, options) => {
  try {
    return { result: await agent(prompt, options), failure: null };
  } catch (error) {
    return {
      result: null,
      failure: error?.message || String(error),
    };
  }
};

phase("retrieve-evidence");
const retrievalAttempt = await invokeAgent(
  adapterPrompt(
    "retrieval",
    "Use only the plugin's read-only biblical-data MCP tools. Assign stable evidence IDs, preserve passage anchors, record every attempted tool and its outcome, and set datasetVersion to null when the tool does not report one.",
    { request },
  ),
  {
    label: "retrieval",
    agentType: "claude-of-alexandria:deep-study-retrieval",
    schema: evidenceSchema,
  },
);
if (retrievalAttempt.failure !== null) {
  return stoppedReport("retrieval", "The retrieval agent could not run: " + retrievalAttempt.failure);
}
const retrieval = retrievalAttempt.result;

if (retrieval === null) {
  return stoppedReport("retrieval", "The retrieval agent returned null, so its work cannot be treated as an empty evidence set.");
}
stageOutcomes.retrieval = retrieval.status;
if (retrieval.status === "unavailable") {
  return {
    status: "incomplete",
    stageOutcomes,
    validationErrors: ["Essential evidence is unavailable."],
    renderedReport: "# Incomplete deep study\n\nEssential evidence is unavailable, so dependent analysis did not run.",
  };
}

phase("assess-boundary");
const boundaryAttempt = await invokeAgent(
  adapterPrompt(
    "boundary-analysis",
    "Assess whether the requested passage should be retained, expanded, or contracted. The recommendation is advisory: all later stages must continue to identify the user's requested passage unchanged.",
    { request, evidence: retrieval },
  ),
  {
    label: "boundary",
    agentType: "claude-of-alexandria:deep-study-analysis",
    schema: analysisSchema,
  },
);
if (boundaryAttempt.failure !== null) {
  return stoppedReport("boundary", "The boundary agent could not run: " + boundaryAttempt.failure);
}
const boundary = boundaryAttempt.result;
if (boundary === null) {
  return stoppedReport("boundary", "The boundary agent returned null; no boundary recommendation is available.");
}
stageOutcomes.boundary = boundary.status;

phase("analyze");
const [discourseAttempt, interpretationAttempt] = await parallel([
  () => invokeAgent(
    adapterPrompt(
      "discourse-analysis",
      "Analyze the literary and discourse movement. Every claim must have a stable claim ID, passage anchors, and only evidence IDs present in the evidence bundle.",
      { request, evidence: retrieval, boundary },
    ),
    {
      label: "discourse",
      agentType: "claude-of-alexandria:deep-study-analysis",
      schema: analysisSchema,
    },
  ),
  () => invokeAgent(
    adapterPrompt(
      "historical-theological interpretation",
      "Develop a text-led interpretation that distinguishes direct evidence from inference. Every claim must have a stable claim ID, passage anchors, and only evidence IDs present in the evidence bundle.",
      { request, evidence: retrieval, boundary },
    ),
    {
      label: "interpretation",
      agentType: "claude-of-alexandria:deep-study-analysis",
      schema: analysisSchema,
    },
  ),
]);
if (discourseAttempt.failure !== null || interpretationAttempt.failure !== null) {
  const failures = [discourseAttempt.failure, interpretationAttempt.failure].filter(Boolean);
  return stoppedReport("analysis", "One or more analysis agents could not run: " + failures.join("; "));
}
const discourse = discourseAttempt.result;
const interpretation = interpretationAttempt.result;
if (discourse === null || interpretation === null) {
  return stoppedReport("analysis", "One or more analysis agents returned null; partial work is preserved but cannot be silently promoted.");
}
stageOutcomes.discourse = discourse.status;
stageOutcomes.interpretation = interpretation.status;

phase("verify");
let analysis = { discourse, interpretation };
let verificationAttempt = await invokeAgent(
  adapterPrompt(
    "independent verification",
    "Check every claim against the complete evidence bundle, flag unknown IDs, unsupported claims, overstated certainty, and ignored tool failures. Do not repair the analysis yourself.",
    { request, evidence: retrieval, boundary, analysis },
  ),
  {
    label: "verification",
    agentType: "claude-of-alexandria:deep-study-verification",
    schema: verificationSchema,
  },
);
if (verificationAttempt.failure !== null) {
  return stoppedReport("verification", "The verifier could not run: " + verificationAttempt.failure);
}
let verification = verificationAttempt.result;
if (verification === null) {
  return stoppedReport("verification", "The verifier returned null, so no verification result exists.");
}
stageOutcomes.verification = verification.status;

if (verification.status === "needs_repair") {
  if (verification.repairTargets.length === 0) {
    return stoppedReport("repair", "Verification requested repair without naming any repair target.");
  }
  phase("repair-once");
  const repairAttempt = await invokeAgent(
    adapterPrompt(
      "targeted repair",
      "Repair only the named targets. Preserve valid claims and identifiers, disclose anything that remains unresolved, and do not broaden the requested passage.",
      { request, evidence: retrieval, boundary, analysis, verification },
    ),
    {
      label: "repair",
      agentType: "claude-of-alexandria:deep-study-analysis",
      schema: analysisSchema,
    },
  );
  if (repairAttempt.failure !== null) {
    return stoppedReport("repair", "The single permitted repair could not run: " + repairAttempt.failure);
  }
  const repair = repairAttempt.result;
  if (repair === null) {
    return stoppedReport("repair", "The single permitted repair returned null; no second repair will be attempted.");
  }
  stageOutcomes.repair = repair.status;
  if (repair.status === "failed") {
    return stoppedReport("repair", "The single permitted repair failed; no second repair will be attempted.");
  }
  analysis = { ...analysis, repair };
  verificationAttempt = await invokeAgent(
    adapterPrompt(
      "independent re-verification",
      "Re-check the repaired targets and the full claim set. This is the final verification pass; request no further repair cycle.",
      { request, evidence: retrieval, boundary, analysis, priorVerification: verification },
    ),
    {
      label: "reverify",
      agentType: "claude-of-alexandria:deep-study-verification",
      schema: verificationSchema,
    },
  );
  if (verificationAttempt.failure !== null) {
    return stoppedReport("reverify", "The final re-verification could not run: " + verificationAttempt.failure);
  }
  verification = verificationAttempt.result;
  if (verification === null) {
    return stoppedReport("reverify", "The final re-verification returned null; no additional attempt will run.");
  }
  stageOutcomes.reverify = verification.status;
}

phase("synthesize");
const synthesisAttempt = await invokeAgent(
  adapterPrompt(
    "final synthesis",
    "Write in the requested output language. Preserve the requested passage and research question. Cite claim and evidence IDs exactly, list unresolved claims and limitations, and report incomplete status unless verification is verified.",
    { request, evidence: retrieval, boundary, analysis, verification },
  ),
  {
    label: "synthesis",
    agentType: "claude-of-alexandria:deep-study-synthesis",
    schema: finalReportSchema,
  },
);
if (synthesisAttempt.failure !== null) {
  return stoppedReport("synthesis", "The synthesis agent could not run: " + synthesisAttempt.failure);
}
const synthesis = synthesisAttempt.result;
if (synthesis === null) {
  return stoppedReport("synthesis", "The synthesis agent returned null, so no final report was produced.");
}
stageOutcomes.synthesis = synthesis.status;

const knownEvidenceIds = new Set(retrieval.evidence.map((item) => item.id));
const allEvidenceIds = retrieval.evidence.map((item) => item.id);
const claims = Object.values(analysis).flatMap((item) => item?.claims ?? []);
const knownClaimIds = new Set(
  claims.map((claim) => claim.id),
);
const validationErrors = [];
if (knownEvidenceIds.size !== allEvidenceIds.length) {
  validationErrors.push("Evidence IDs are not unique.");
}
for (const evidenceId of boundary.evidenceIds ?? []) {
  if (!knownEvidenceIds.has(evidenceId)) {
    validationErrors.push("Boundary references unknown evidence: " + evidenceId);
  }
}
for (const claim of claims) {
  for (const evidenceId of claim.evidenceIds) {
    if (!knownEvidenceIds.has(evidenceId)) {
      validationErrors.push("Claim " + claim.id + " references unknown evidence: " + evidenceId);
    }
  }
}
for (const evidenceId of synthesis.evidenceReferences) {
  if (!knownEvidenceIds.has(evidenceId)) {
    validationErrors.push("Unknown evidence reference: " + evidenceId);
  }
}
for (const claimId of synthesis.claimReferences) {
  if (!knownClaimIds.has(claimId)) {
    validationErrors.push("Unknown claim reference: " + claimId);
  }
}
for (const finding of verification.findings) {
  if (!knownClaimIds.has(finding.claimId)) {
    validationErrors.push("Verification references unknown claim: " + finding.claimId);
  }
  for (const evidenceId of finding.evidenceIds) {
    if (!knownEvidenceIds.has(evidenceId)) {
      validationErrors.push("Verification references unknown evidence: " + evidenceId);
    }
  }
}
for (const claimId of [...verification.repairTargets, ...verification.unresolvedClaims]) {
  if (!knownClaimIds.has(claimId)) {
    validationErrors.push("Verification status references unknown claim: " + claimId);
  }
}
if (synthesis.requestedPassage !== request.passage) {
  validationErrors.push("Final report changed the requested passage.");
}
if (synthesis.researchQuestion !== request.researchQuestion) {
  validationErrors.push("Final report changed the research question.");
}
if ([boundary, discourse, interpretation].some((stage) => stage.status === "failed")) {
  validationErrors.push("A required analysis stage failed.");
}

const verified = verification.status === "verified" && verification.unresolvedClaims.length === 0;
if (!verified) {
  validationErrors.push("Verification did not finish with all claims resolved.");
}
if (validationErrors.length > 0) {
  const heading = validationErrors.some((error) => /reference/i.test(error))
    ? "Reference validation failed:"
    : "Report validation failed:";
  return {
    ...synthesis,
    status: "incomplete",
    stageOutcomes,
    validationErrors,
    renderedReport: "# Incomplete deep study\n\n" + heading + "\n\n" + validationErrors.map((error) => "- " + error).join("\n") + "\n\n" + synthesis.renderedReport,
  };
}

return {
  ...synthesis,
  status: synthesis.status === "complete" && verified ? "complete" : "incomplete",
  stageOutcomes,
  validationErrors,
};
