#!/usr/bin/env python3
"""
Versification ETL — extract Hebrew-English verse mappings from UBS eng.json.

Downloads the UBS Paratext versification data and generates SQL seed file
mapping English (Protestant) verse numbering to Hebrew (Masoretic) numbering.

Usage:
    cd server && python3 scripts/extract-versification.py

Output:
    d1-seed/versification.sql

Source:
    UBS/Paratext versification_json (MIT License)
    https://github.com/ubsicap/versification_json
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

# ─── Source URL ───────────────────────────────────────────────────────────────
ENG_JSON_URL = (
    "https://raw.githubusercontent.com/ubsicap/versification_json/"
    "master/examples/eng.json"
)

SEED_DIR = Path(__file__).resolve().parent.parent / "d1-seed"
OUTPUT_FILE = SEED_DIR / "versification.sql"

# ─── OSIS abbreviation → canonical book name ─────────────────────────────────
OSIS_TO_CANONICAL = {
    "GEN": "Genesis", "EXO": "Exodus", "LEV": "Leviticus", "NUM": "Numbers",
    "DEU": "Deuteronomy", "JOS": "Joshua", "JDG": "Judges", "RUT": "Ruth",
    "1SA": "1 Samuel", "2SA": "2 Samuel", "1KI": "1 Kings", "2KI": "2 Kings",
    "1CH": "1 Chronicles", "2CH": "2 Chronicles", "EZR": "Ezra", "NEH": "Nehemiah",
    "EST": "Esther", "JOB": "Job", "PSA": "Psalms", "PRO": "Proverbs",
    "ECC": "Ecclesiastes", "SNG": "Song of Songs", "ISA": "Isaiah", "JER": "Jeremiah",
    "LAM": "Lamentations", "EZK": "Ezekiel", "DAN": "Daniel", "HOS": "Hosea",
    "JOL": "Joel", "AMO": "Amos", "OBA": "Obadiah", "JON": "Jonah",
    "MIC": "Micah", "NAM": "Nahum", "HAB": "Habakkuk", "ZEP": "Zephaniah",
    "HAG": "Haggai", "ZEC": "Zechariah", "MAL": "Malachi",
}

# Books to skip (apocryphal/deuterocanonical)
SKIP_BOOKS = {"BAR", "DAG", "ESG", "S3Y", "LJE", "SUS", "BEL"}


def sql_escape(value):
    """Escape single quotes for SQL string literals."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def parse_ref(ref_str):
    """Parse a reference like 'GEN 32:1' or 'GEN 32:1-33' into components.

    Returns (book_abbrev, chapter, verse_start, verse_end) where verse_end
    may be None for single-verse references.
    """
    match = re.match(r"^(\w+)\s+(\d+):(\d+)(?:-(\d+))?$", ref_str.strip())
    if not match:
        return None
    book = match.group(1)
    chapter = int(match.group(2))
    verse_start = int(match.group(3))
    verse_end = int(match.group(4)) if match.group(4) else None
    return (book, chapter, verse_start, verse_end)


def expand_mappings(mapped_verses):
    """Expand range mappings into individual versification rows.

    Each entry maps English versification → Hebrew versification.
    For ranges like 'GEN 32:1-32' -> 'GEN 32:2-33', we create one row
    representing the range offset.
    """
    rows = []
    skipped = 0

    for eng_ref, heb_ref in mapped_verses.items():
        eng_parsed = parse_ref(eng_ref)
        heb_parsed = parse_ref(heb_ref)

        if not eng_parsed or not heb_parsed:
            skipped += 1
            continue

        eng_book, eng_ch, eng_vs, eng_ve = eng_parsed
        heb_book, heb_ch, heb_vs, heb_ve = heb_parsed

        # Skip apocryphal books
        if eng_book in SKIP_BOOKS or heb_book in SKIP_BOOKS:
            skipped += 1
            continue

        # Skip if book not in our canonical list
        if eng_book not in OSIS_TO_CANONICAL:
            skipped += 1
            continue

        canonical_name = OSIS_TO_CANONICAL[eng_book]

        # Determine mapping type
        if eng_ch != heb_ch:
            mapping_type = "chapter_boundary"
        elif eng_vs != heb_vs:
            mapping_type = "offset"
        else:
            mapping_type = "offset"

        rows.append({
            "book": canonical_name,
            "english_chapter": eng_ch,
            "english_verse_start": eng_vs,
            "english_verse_end": eng_ve,
            "hebrew_chapter": heb_ch,
            "hebrew_verse_start": heb_vs,
            "hebrew_verse_end": heb_ve,
            "mapping_type": mapping_type,
        })

    return rows, skipped


def write_sql(rows, output_path):
    """Write versification rows as SQL INSERT statements."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated by extract-versification.py\n")
        f.write("-- Source: UBS/Paratext versification_json (MIT License)\n\n")

        batch_size = 50
        for i in range(0, len(rows), batch_size):
            batch = rows[i : i + batch_size]
            f.write(
                "INSERT OR REPLACE INTO versification "
                "(book, english_chapter, english_verse_start, english_verse_end, "
                "hebrew_chapter, hebrew_verse_start, hebrew_verse_end, mapping_type) VALUES\n"
            )
            sql_rows = []
            for r in batch:
                sql_rows.append(
                    f"({sql_escape(r['book'])}, "
                    f"{r['english_chapter']}, "
                    f"{r['english_verse_start']}, "
                    f"{r['english_verse_end'] if r['english_verse_end'] is not None else 'NULL'}, "
                    f"{r['hebrew_chapter']}, "
                    f"{r['hebrew_verse_start']}, "
                    f"{r['hebrew_verse_end'] if r['hebrew_verse_end'] is not None else 'NULL'}, "
                    f"{sql_escape(r['mapping_type'])})"
                )
            f.write(",\n".join(sql_rows))
            f.write(";\n\n")

    print(f"Wrote {len(rows)} rows to {output_path}")


def main():
    # Download
    print("Downloading UBS eng.json...")
    try:
        req = urllib.request.Request(
            ENG_JSON_URL,
            headers={"User-Agent": "claude-of-alexandria-etl/1.0"},
        )
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        print(f"ERROR: Failed to download: {e}", file=sys.stderr)
        sys.exit(1)

    mapped_verses = data.get("mappedVerses", {})
    print(f"  Total mappedVerses entries: {len(mapped_verses)}")

    # Parse and expand
    rows, skipped = expand_mappings(mapped_verses)
    print(f"  Canonical rows: {len(rows)}")
    print(f"  Skipped (apocryphal/unparseable): {skipped}")

    # Sanity checks
    if len(rows) < 50:
        print(f"ERROR: Expected at least 50 rows, got {len(rows)}", file=sys.stderr)
        sys.exit(1)

    # Spot-check: Genesis 31:55 → Genesis 32:1
    gen_check = [
        r for r in rows
        if r["book"] == "Genesis"
        and r["english_chapter"] == 31
        and r["english_verse_start"] == 55
    ]
    if gen_check:
        r = gen_check[0]
        print(
            f"\nSpot-check: Genesis {r['english_chapter']}:{r['english_verse_start']} "
            f"→ Hebrew {r['hebrew_chapter']}:{r['hebrew_verse_start']}"
        )
    else:
        print("WARNING: Genesis 31:55 mapping not found", file=sys.stderr)

    # Write SQL
    write_sql(rows, OUTPUT_FILE)
    print("\nDone.")


if __name__ == "__main__":
    main()
